/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/house.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/house.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.305}>
        <mesh geometry={nodes.Aluminium002.geometry} material={materials['Aluminium.002']} />
        <mesh geometry={nodes.Aluminium002_1.geometry} material={materials['Default material.002']} />
        <mesh geometry={nodes.Aluminium002_2.geometry} material={materials['White Plaster.002']} />
        <mesh geometry={nodes.Aluminium002_3.geometry} material={materials['Concrete Masonry Units.002']} />
        <mesh geometry={nodes.Aluminium002_4.geometry} material={materials['Timber - White.002']} />
        <mesh geometry={nodes.Aluminium002_5.geometry} material={materials['White Tile.002']} />
        <mesh geometry={nodes.Aluminium002_6.geometry} material={materials['Structure, Steel Bar Joist Layer.002']} />
        <mesh geometry={nodes.Aluminium002_7.geometry} material={materials['Kovácsoltvas.002']} />
        <mesh geometry={nodes.Aluminium002_8.geometry} material={materials['Kovácsoltvas-White Porcelain.002']} />
        <mesh geometry={nodes.Aluminium002_9.geometry} material={materials['Fence Patterned Cream Brick.002']} />
        <mesh geometry={nodes.Aluminium002_10.geometry} material={materials['Rigid insulation.002']} />
        <mesh geometry={nodes.Aluminium002_11.geometry} material={materials['Roof - Green Tiles.002']} />
        <mesh geometry={nodes.Aluminium002_12.geometry} material={materials['Marble.002']} />
        <mesh geometry={nodes.Aluminium002_13.geometry} material={materials['White Porcelain.002']} />
        <mesh geometry={nodes.Aluminium002_14.geometry} material={materials['Diamond Mesh.002']} />
        <mesh geometry={nodes.Aluminium002_15.geometry} material={materials['Finish.002']} />
        <mesh geometry={nodes.Aluminium002_16.geometry} material={materials['Timber - Grey.002']} />
        <mesh geometry={nodes.Aluminium002_17.geometry} material={materials['Default.002']} />
        <mesh geometry={nodes.Aluminium002_18.geometry} material={materials['Concrete.002']} />
        <mesh geometry={nodes.Aluminium002_19.geometry} material={materials['Glass (2).002']} />
        <mesh geometry={nodes.Aluminium002_20.geometry} material={materials['Roofing, Slate.002']} />
        <mesh geometry={nodes.Aluminium002_21.geometry} material={materials['SANINDUSA Vitreous China.002']} />
        <mesh geometry={nodes.Aluminium002_22.geometry} material={materials['Grass.002']} />
        <mesh geometry={nodes.Aluminium002_23.geometry} material={materials['Plaster, Ivory, Matte.002']} />
        <mesh geometry={nodes.Aluminium002_24.geometry} material={materials['Masonry - Brick - Cream.002']} />
        <mesh geometry={nodes.Aluminium002_25.geometry} material={materials['Masonry - Brick - Green.002']} />
        <mesh geometry={nodes.Aluminium002_26.geometry} material={materials['Masonry - Brick - Terracotta.002']} />
        <mesh geometry={nodes.Aluminium002_27.geometry} material={materials['Timber.002']} />
        <mesh geometry={nodes.Aluminium002_28.geometry} material={materials['Glass.002']} />
        <mesh geometry={nodes.Aluminium002_29.geometry} material={materials['Ceiling.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/house.glb')
